name: Simple workflow for a Node.js application

on:
  push:

env:
  node-version: 14.x # 10.x, 12.x, 14.x, 15.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build if neccessary
        run: npm run build --if-present
      - run: npm run test
